name: CICD

on:
  push:

jobs:
  cicd:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up JDK for x64
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64
      - run: mvn package
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: registry.himadri.eu/kavai77/passwordmanager:latest
          build-args: |
            JAR_FILE=target/passwordmanager-*.jar
